apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_type: manual
    env: debug
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
